Repository umgc/spring2023, pull requests merged in 2023-03, with the labels that each got.

#33 Hamburger menu
  virotour/lib/main.dart
  virotour/lib/src/hamburger.dart
  virotour/lib/src/settings/settings_view.dart
  virotour/lib/src/tour/tour_list_view.dart
Labels: team A

#59 Glow feature backend use
  virotour/lib/src/tour/glow_effect.dart
  virotour/lib/src/tour/glow_feature_backend.dart
Labels: team A

#67 Add tested features for Flutter app
  README.md
  virotour/README.md
  virotour/assets/images/android_issues/connection_refused.png
  virotour/docs/android_issues.md
  virotour/lib/main.dart
  virotour/lib/src/app.dart
  virotour/lib/src/navbar/hamburger.dart
  virotour/lib/src/search/hotspot_search_view.dart
  virotour/lib/src/settings/settings_view.dart
  virotour/lib/src/tour/tour_details_view.dart
  virotour/lib/src/tour/tour_list_view.dart
  virotour/pubspec.yaml
  virotour_local/README.md
  virotour_local/flask/README.md
  virotour_local/flask/app/api/compute/blur_faces_util/haarcascade_frontalface_default.xml
  virotour_local/flask/app/api/compute/image_blur_faces.py
  virotour_local/flask/app/api/compute/pano_util/stitch.py
  virotour_local/flask/app/app.db
  virotour_local/flask/app/tests/compute/test_image_blur_faces.py
  virotour_local/flask/app/tests/images/input_images/messi.png
  virotour_local/helpers/setup_macos.sh
  virotour_local/helpers/start_flask_server.sh
Labels: both teams

#57 Basic Tours Search
  virotour/lib/src/navbar/hamburger.dart
  virotour/lib/src/search.dart
Labels: invalid, team A

#75 glow effect using tour view image
  virotour/lib/src/settings/settings_view.dart
  virotour/lib/src/tour/glow_feature_backend_view.dart
  virotour/lib/src/tour/tour_details_view.dart
Labels: team A

#36 Create tour page
  virotour/README.md
  virotour/ios/Runner/Info.plist
  virotour/lib/src/app.dart
  virotour/lib/src/navbar/hamburger.dart
  virotour/lib/src/tour/tour_create_view.dart
  virotour/lib/src/tour/tour_edit_view.dart
  virotour/pubspec.yaml
  virotour/test/widget_test.dart
Labels: team A
